from __future__ import annotations

import tempfile
import unittest
from pathlib import Path

from video2notes.audio import (
    SubtitleParseError,
    parse_subtitle_file,
    parse_subtitle_text,
    parse_subtitle_timestamp,
)
from video2notes.domain import EvidenceModality


class SubtitleParserTests(unittest.TestCase):
    def test_srt_supports_bom_decimal_variants_languages_and_overlap(self) -> None:
        payload = (
            "\ufeff1\r\n"
            "00:00:01,250 --> 00:00:03.000\r\n"
            "<lang zh-CN><v Alice>你好 &amp; hello</v></lang>\r\n"
            "\r\n"
            "2\r\n"
            "00:00:02.500 --> 00:00:04,75\r\n"
            "second cue\r\n"
        )
        with tempfile.TemporaryDirectory() as temporary:
            path = Path(temporary) / "mixed.srt"
            path.write_bytes(payload.encode("utf-8"))
            cues = parse_subtitle_file(
                path,
                run_id="run-1",
                language="en",
                timeline_offset_us=100_000,
            )

        self.assertEqual(len(cues), 2)
        self.assertEqual(cues[0].modality, EvidenceModality.PLATFORM_CAPTION)
        self.assertEqual((cues[0].start_us, cues[0].end_us), (1_350_000, 3_100_000))
        self.assertEqual(cues[0].language, "zh-CN")
        self.assertEqual(cues[0].speaker, "Alice")
        self.assertEqual(cues[0].raw_text, "你好 & hello")
        self.assertEqual(cues[1].language, "en")
        self.assertEqual((cues[1].start_us, cues[1].end_us), (2_600_000, 4_850_000))
        self.assertLess(cues[1].start_us, cues[0].end_us, "overlap must be preserved")

    def test_webvtt_header_identifier_note_and_settings(self) -> None:
        payload = """WEBVTT
Language: ja

NOTE generated by platform
do not parse this

cue-a
00:01.250 --> 00:02,500 align:start position:10%
最初の行
二行目
"""
        cues = parse_subtitle_text(payload, run_id="run-vtt", source_name="ja.vtt")

        self.assertEqual(len(cues), 1)
        self.assertEqual(cues[0].language, "ja")
        self.assertEqual(cues[0].start_us, 1_250_000)
        self.assertEqual(cues[0].end_us, 2_500_000)
        self.assertEqual(cues[0].raw_text, "最初の行\n二行目")
        self.assertEqual(cues[0].provenance["cue_identifier"], "cue-a")

    def test_utf16_bom_subtitle_file_is_detected(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            path = Path(temporary) / "utf16.srt"
            path.write_bytes("1\n00:00:00,100 --> 00:00:00,900\nПривет\n".encode("utf-16"))
            cues = parse_subtitle_file(path, run_id="run-utf16", language="ru")

        self.assertEqual(len(cues), 1)
        self.assertEqual(cues[0].raw_text, "Привет")
        self.assertEqual(cues[0].language, "ru")

    def test_timestamp_uses_decimal_arithmetic(self) -> None:
        self.assertEqual(parse_subtitle_timestamp("01:02.5"), 62_500_000)
        self.assertEqual(parse_subtitle_timestamp("1:02:03,004"), 3_723_004_000)

    def test_negative_canonical_offset_is_rejected(self) -> None:
        with self.assertRaisesRegex(SubtitleParseError, "negative"):
            parse_subtitle_text(
                "00:00:00.100 --> 00:00:00.200\ntext\n",
                run_id="run",
                timeline_offset_us=-200_000,
            )


if __name__ == "__main__":
    unittest.main()
