"""Source acquisition adapters for local files, Bilibili, YouTube, and X."""

from video2notes.sources.browser_profiles import enumerate_browser_profiles
from video2notes.sources.errors import (
    AcquisitionCancelled,
    CancellationToken,
    QualityChangedError,
    SourceAcquisitionError,
    SourceError,
    SourceProbeError,
    UnsupportedSourceError,
)
from video2notes.sources.local import LocalFileAdapter
from video2notes.sources.models import (
    AcquisitionPolicy,
    AcquisitionResult,
    AuthKind,
    AuthSpec,
    BrowserKind,
    BrowserProfile,
    FormatInfo,
    Platform,
    ProgressEvent,
    ProgressKind,
    QualityMode,
    SourceInput,
    SourceKind,
    SourceManifest,
)
from video2notes.sources.registry import (
    SourceAdapter,
    SourceRegistry,
    parse_supported_url,
    platform_for_url,
)
from video2notes.sources.ytdlp import (
    EXPECTED_YT_DLP_VERSION,
    BilibiliAdapter,
    XAdapter,
    YouTubeAdapter,
    YtDlpAdapter,
    format_selection_fingerprint,
    progress_event_from_ytdlp,
    redact_sensitive,
    select_exact_formats,
)

__all__ = [
    "EXPECTED_YT_DLP_VERSION",
    "AcquisitionCancelled",
    "AcquisitionPolicy",
    "AcquisitionResult",
    "AuthKind",
    "AuthSpec",
    "BilibiliAdapter",
    "BrowserKind",
    "BrowserProfile",
    "CancellationToken",
    "FormatInfo",
    "LocalFileAdapter",
    "Platform",
    "ProgressEvent",
    "ProgressKind",
    "QualityChangedError",
    "QualityMode",
    "SourceAcquisitionError",
    "SourceAdapter",
    "SourceError",
    "SourceInput",
    "SourceKind",
    "SourceManifest",
    "SourceProbeError",
    "SourceRegistry",
    "UnsupportedSourceError",
    "XAdapter",
    "YouTubeAdapter",
    "YtDlpAdapter",
    "enumerate_browser_profiles",
    "format_selection_fingerprint",
    "parse_supported_url",
    "platform_for_url",
    "progress_event_from_ytdlp",
    "redact_sensitive",
    "select_exact_formats",
]
